spring:
  datasource:
    username: root
    password: 11111111
    url: jdbc:mysql://localhost:3306/springbatch?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    initialization-mode: never
